Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'α',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'β',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'δ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'ε',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'θ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'λ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'μ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'π',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'φ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'ψ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Maths Symbols',N'Ω',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁰',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'¹',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'²',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'³',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁴',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁵',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁶',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁷',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁸',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁹',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁺',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁻',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁼',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁽',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'⁾',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'ⁿ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SuperScript',N'ⁱ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₀',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₁',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₂',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₃',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₄',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₅',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₆',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₇',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₈',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₉',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₊',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₋',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₌',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₍',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'₎',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₐ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₑ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₕ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ᵢ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ⱼ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₖ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₗ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₘ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₙ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₒ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₚ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ᵣ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₛ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₜ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ᵤ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ᵥ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₓ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubScript',N'ₔ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Roots',N'√',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Roots',N'∛',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'Roots',N'∜',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'∅',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⦰',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⦱',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⦲',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⦳',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⦴',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'ℵ',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'∈',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'∋',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'∉',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'∌',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋶',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋽',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋲',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋺',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋳',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋻',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'∊',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'∍',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋷',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋾',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋴',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋼',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋵',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋸',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⋹',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⫙',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SETS',N'⟒',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊂',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊃',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊄',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊅',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊆',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊇',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊈',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊉',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊊',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⊋',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⫅',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⫆',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⫋',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⫌',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⫇',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⫈',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⫉',GETDATE(),GETDATE())
Insert Into TextLists (TextListId,[Group],[Text],InsertedOn,LastUpdatedOn)Values(NewId(),'SubSet',N'⫊',GETDATE(),GETDATE())
